# merged_context.py
# THIS FILE IS AUTOMATICALLY GENERATED FOR LLM CONTEXT
# It concatenates several modules without modifying them.

# --- translation_service.py ---
"""
this is another low-level module. I will be calling it just once during initialization ig
"""

import logging

import httpx  # type: ignore
from redis.asyncio import Redis

from backend.services.translator.config import get_settings
from game_internals.core.schemas.game_settings import languages

logger = logging.getLogger(__name__)
settings = get_settings()  # for building URL


BASE_URL = settings.base_url
email = settings.personal_email
cache_time = settings.cache_time


async def translate(text: str, to_language: languages, redis: Redis) -> str:
    """
    this ALWAYS translates from English since the app assumes it as the default language.
    therefore, this function is also tailored to translate from english only
    """
    cache = f"translation:{to_language}:{hash(text)}"  # acts as key:value because it is

    cached = await redis.get(cache)
    if cached:
        return cached

    # mymemory api is url-based, it parses, therefore i build URL dynamically
    params = {"q": text, "langpair": f"en|{to_language}", "de": email}
    try:
        async with httpx.AsyncClient() as client:
            r = await client.get(str(BASE_URL), params=params)
            r.raise_for_status()  # fails loudly if goes south
    except httpx.HTTPStatusError as e:
        logger.error("Mymemory responded with 4xx or 5xx: %s", e)
        raise
    except httpx.RequestError as e:  # generic httpx error
        logger.error("Mymemory error while requesting data: %s", e)
        raise

    result = r.json()["responseData"]["translatedText"]

    await redis.set(cache, result, ex=cache_time)  # in seconds
    logger.info("Text %s cached for %s hours", text, cache_time // 3600)  # in hours
    return result


# --- cache_warm.py ---
"""
This creates cache as soon as the app launches with 1 async function
its low-level too, so as everywhere else, i'll handle it
on the most abstracted layer. Not here.
"""

from redis.asyncio import Redis


async def warm_cache(collection: list, redis: Redis):
    """
    the collection is all the phrases and whatnot...
    """
    pass
    # await asyncio.gather(*tasks)


# --- game_settings.py ---
import logging

from redis.asyncio import Redis
from sqlalchemy.ext.asyncio import AsyncSession

from backend.models.players import Player
from game_internals.core.schemas.game_settings import GameSettings, languages

logger = logging.getLogger(__name__)


class GameSettingsService:
    def __init__(self, db: AsyncSession, redis: Redis):
        self.db = db
        self.redis = redis

    async def get_settings(self, player: Player) -> GameSettings:
        """get player settings, cache if needed"""

        cached = await self.redis.get(f"settings:{player.id}")
        if cached:
            return GameSettings.model_validate_json(cached)

        # validate settings
        settings = GameSettings.model_validate(
            player.preferences or {}
        )  # getting brackets would mean a bug
        if settings == {}:
            logger.warning("Expected settings, got an empty dictionary")

        await self.redis.set(
            f"settings:{player.id}", settings.model_dump_json(), ex=7200
        )
        logger.info("Settings cached for %s", player.id)
        return settings

    async def update_settings(self, player: Player, **kwargs) -> GameSettings:
        """update settings by passing only required fields"""

        current_settings = await self.get_settings(player)
        updated_settings = GameSettings.model_validate(
            current_settings.model_dump() | kwargs
        )  # merges and validates
        player.preferences = updated_settings.model_dump()

        self.db.add(player)
        await self.db.commit()
        logger.info("Settings updated for %s", player.id)

        await self.redis.set(
            f"settings:{player.id}", updated_settings.model_dump_json(), ex=7200
        )
        logger.info("Settings cached for %s", player.id)
        return updated_settings

    # high level function
    async def update_language(self, player: Player, language: languages):
        """Abstraction built upon update_settings()"""

        try:
            updated = await self.update_settings(player, current_language=language)

        except Exception as e:
            logger.error("Exception occured: %s", e)
            raise

        return updated


# --- redis.py ---
import redis.asyncio as redis
from redis.asyncio import Redis

from backend.core.config import get_settings

settings = get_settings()


async def get_redis() -> Redis:
    redis_client = redis.from_url(
        str(settings.redis_url), encoding="utf-8", decode_responses=True
    )
    return redis_client


# --- events.py ---
"""Event helpers for the game.

This module is intentionally minimal; individual event functions are
declared with the expected signature but contain no real logic.  The idea
is to provide a starting point for you to implement behaviour as you
incrementally refactor the repository.

Each function accepts a ``player`` object (type is ``Any`` here to avoid
hard dependencies) and returns a dictionary describing the event.  The
returned structure is arbitrary and may be changed later.
"""

from __future__ import annotations

from typing import Any, Optional


def heal_event(player: Any) -> dict:
    """Player receives a small heal."""

    # TODO: decide amount and update player
    return {"type": "heal", "value": 0}


def random_item_event(player: Any) -> dict:
    """Give the player a randomly chosen item."""

    return {"type": "random item", "value": None}


def floor_up_event(player: Any) -> dict:
    """Advance the player's floor/level by one (occasionally two)."""

    return {"type": "floor_up", "value": 0}


def add_coins_event(player: Any) -> dict:
    """Award the player some coins."""

    return {"type": "add coins", "value": 0}


def summon_enemy_event(player: Any, enemy: Optional[str] = None) -> dict:
    """Trigger an enemy encounter.

    :param enemy: optional key to force a specific opponent
    """

    return {"type": "enemy", "value": enemy, "report": None}


def poison_event(player: Any) -> dict:
    """Inflict poison damage on the player."""

    return {"type": "poison", "value": 0}


def floor_down_event(player: Any) -> dict:
    """Decrease the player's floor/level."""

    return {"type": "floor_down", "value": 0}


# --- items_operations.py ---
import logging
from random import choices

from game_internals.core.gameplay.equipment.items_list import (
    CATALOG,
    CATEGORIES,
    CATEGORIES_TYPES,
)
from game_internals.core.schemas.items import (
    Accessory,
    Gear,
    ShieldOnly,
    TwoHanded,
    WeaponAndShield,
    WeaponOnly,
)

logger = logging.getLogger(__name__)


def pick_rand_item_by_category(
    category: CATEGORIES_TYPES,
) -> Gear | Accessory | WeaponOnly | WeaponAndShield | ShieldOnly | TwoHanded:
    if category not in CATEGORIES:
        # in dev this will raise, but if not tested, logs are helpful
        logger.error(
            "Potential bug: invalid category passed for arg 'category': got %s",
            category,
        )
        raise TypeError("Invalid category provided")

    # CATALOG contains all values filtered by the category

    category_items = {k: v for k, v in CATALOG.items() if v.slot == category}
    chosen_key = choices(
        list(category_items.keys()),
        weights=[v.drop_rate for v in category_items.values()],
        k=1,
    )[0]
    final_item = category_items[chosen_key]

    return final_item  # validated pydantic model


def pick_random_item() -> (
    Gear | Accessory | WeaponOnly | WeaponAndShield | ShieldOnly | TwoHanded
):
    """
    same logic but not choosing category here
    """
    chosen_key = choices(
        list(CATALOG.keys()),
        weights=[v.drop_rate for v in CATALOG.values()],
        k=1,
    )[0]
    final_item = CATALOG[chosen_key]

    return final_item  # validated pydantic model
